In [2]:
import numpy as np

In [85]:
list=[1,2,3]
list

[1, 2, 3]

In [29]:
A=np.array(list)
A

array([1, 2, 3])

In [8]:
list1=[[1,2,3],[4,5,6],[7,8,9]]

In [30]:
B=np.array(list1)
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
C=np.arange(0,10)
C

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
D=np.arange(0,11,2)
D

array([ 0,  2,  4,  6,  8, 10])

In [33]:
E=np.zeros(5)
E

array([0., 0., 0., 0., 0.])

In [34]:
F=np.zeros((3,3))
F

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
G=np.ones(6)
G

array([1., 1., 1., 1., 1., 1.])

In [86]:
H=np.ones((3,3))
H

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
I=np.linspace(0,10,3)
I

array([ 0.,  5., 10.])

In [37]:
J=np.eye(3)
J

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
K1=np.random.rand(5)
K1

array([0.37095346, 0.7554968 , 0.11983993, 0.1872461 , 0.5100197 ])

In [61]:
K2=np.random.rand(3,3)
K2

array([[0.11406369, 0.93457219, 0.79056659],
       [0.66322304, 0.4347657 , 0.0626592 ],
       [0.36553395, 0.05309644, 0.50789127]])

In [62]:
L1=np.random.randint(0,100,5)
L1

array([90, 35, 46, 73, 54])

In [63]:
L2=np.random.randint(0,100,9).reshape(3,3)
L2

array([[39, 54, 99],
       [94, 98, 75],
       [ 8, 33, 46]])

In [72]:
M1=np.random.randn(3)
M1

array([-1.6900395 ,  0.87371812, -1.57890132])

In [73]:
M2=np.random.randn(3,3)
M2

array([[-0.95050544, -0.72943944, -0.42048677],
       [ 2.70162803, -0.75194184, -0.736504  ],
       [-0.56772871, -0.26276106, -1.5327934 ]])

In [88]:
N=np.random.randint(0,100,9).reshape(3,3)
N

array([[43, 98, 95],
       [88,  9, 81],
       [64, 76, 22]])

In [76]:
N.max()

92

In [77]:
N.argmax()

9

In [78]:
N.min()

3

In [79]:
N.argmin()

12

In [80]:
N.mean()

41.25

In [82]:
N.var()

684.5625

In [84]:
N.dtype

dtype('int64')