In [2]:
import numpy as np

In [5]:
A=np.arange(0,11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
A[8]

8

In [7]:
A[1:5]

array([1, 2, 3, 4])

In [8]:
A[0:5]

array([0, 1, 2, 3, 4])

In [9]:
A[:5]

array([0, 1, 2, 3, 4])

In [12]:
B=np.arange(11,21)
B

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
C=B[0:6]
C

array([11, 12, 13, 14, 15, 16])

In [16]:
C[0:3]=100
C

array([100, 100, 100,  14,  15,  16])

In [17]:
B

array([100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [19]:
B=np.arange(11,21)
B

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
C=B[0:6].copy()
C

array([11, 12, 13, 14, 15, 16])

In [21]:
C[0:3]=100
C

array([100, 100, 100,  14,  15,  16])

In [22]:
B

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [25]:
D=np.arange(0,9).reshape(3,3)
D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
D[0]

array([0, 1, 2])

In [27]:
D[1]

array([3, 4, 5])

In [32]:
D[0][0]

0

In [33]:
D[0][1]

1

In [35]:
D[0:2,1:3]

array([[1, 2],
       [4, 5]])

In [36]:
D[1:3,0:2]

array([[3, 4],
       [6, 7]])

In [37]:
D>3

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [38]:
D[D>3]

array([4, 5, 6, 7, 8])

In [39]:
E=np.arange(0,6)
E

array([0, 1, 2, 3, 4, 5])

In [40]:
E+E

array([ 0,  2,  4,  6,  8, 10])

In [41]:
E-E

array([0, 0, 0, 0, 0, 0])

In [42]:
E*E

array([ 0,  1,  4,  9, 16, 25])

In [43]:
E+100

array([100, 101, 102, 103, 104, 105])

In [44]:
E-100

array([-100,  -99,  -98,  -97,  -96,  -95])

In [45]:
E/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [46]:
E//2

array([0, 0, 1, 1, 2, 2])

In [47]:
E%2

array([0, 1, 0, 1, 0, 1])